### ISSUE TITLE
Installation issues in combination with docker

### ISSUE THREAD

**Issue by rs-com** [stfnhmplr/homebridge-synology#58]
Hello! I've been dealing with this problem for hours and now have no more ideas...

![Bildschirmfoto 2021-10-28 um 21 47 26 PM](https://user-images.githubusercontent.com/93350156/139329666-b5f5597e-200e-4ff7-b353-8122f98b023f.png)

**Comment by williamli** [comment]
I ran into this issue as well.

**Comment by RS-ela** [comment]
I tried to install the plug-in via the web interface and via the shell in Homebridge (with and without "-g")... to no avail.

**Comment by stfnhmplr** [comment]
It looks like ssh is not installed on your system. Please try to run `sudo apt install openssh-client` and install the plugin again afterwards.

**Comment by domstubbs** [comment]
From what I can see the standard `docker-homebridge` Alpine image has no bundled SSH and this plugin requires it because it references a [forked copy](https://github.com/homeinstalator/syno) of [kwent/syno](https://github.com/kwent/syno) that isn't published to NPM.

If the published kwent/syno package was required instead that would fix this as NPM would use a regular https request to install it, but assuming the fork is being used for a reason, the next best bet would be the Ubuntu `docker-homebridge` image. I assume that comes with ssh bundled, but I've not tried it yet. Installing SSH in the Alpine image should work too but wouldn't persist if you reset the container at any point.

**Comment by domstubbs** [comment]
Switching to the `ubuntu-no-avahi` tag fixes missing SSH but the current dependency setup still triggers a key error on install. If you open the terminal and run `npm install --save homeinstalator/syno#af95c7c` to install the syno dependency manually, then run `npm install --save homebridge-synology@latest` to install the main plugin it does work.

**Comment by stfnhmplr** [comment]
> From what I can see the standard `docker-homebridge` Alpine image has no bundled SSH and this plugin requires it because it references a [forked copy](https://github.com/homeinstalator/syno) of [kwent/syno](https://github.com/kwent/syno) that isn't published to NPM.
> 
> If the published kwent/syno package was required instead that would fix this as NPM would use a regular https request to install it, but assuming the fork is being used for a reason, the next best bet would be the Ubuntu `docker-homebridge` image. I assume that comes with ssh bundled, but I've not tried it yet. Installing SSH in the Alpine image should work too but wouldn't persist if you reset the container at any point.

All of this is correct. The reason for using the [fork](https://github.com/homeinstalator/syno) from homeinstalator is mainly the support for 2FA. Due to an API change, shutting down the diskstation with the original package does not work either. Since related PRs (e.g. [42](https://github.com/kwent/syno/pull/42) for 2FA) are not merged, I decided to go this way.

I did not take into account that this may cause these problems. The best would be if the changes would be merged into the original package.

**Comment by bo-2221** [comment]
Hello, will an update fix the problem?

**Comment by cbrandlehner** [comment]
I used this workaround. My environment is a docker installation with portainer. No kubernetes or docker-swarm.

I connected to a bash console in the homebridge container.

```
cd node_modules
git clone https://github.com/stfnhmplr/homebridge-synology
cd homebridge-synology
npm install
exit
```

**Comment by Vaifranz** [comment]
Same problem, no resolution with the commands in the previous message.

**Comment by bjornand1** [comment]
Me neither, would be nice to get this to work.

**Comment by bjornand1** [comment]
OK, finally figured out the installation issue, I had to install the git package on Synology first.

**Comment by jjss520** [comment]
> 并且，Sology 为已显示，尽管已显示，读数显示。但这可能是什么原因造成的？



> I used this workaround. My environment is a docker installation with portainer. No kubernetes or docker-swarm.
> 
> I connected to a bash console in the homebridge container.
> 
> ```
> cd node_modules
> git clone https://github.com/stfnhmplr/homebridge-synology
> cd homebridge-synology
> npm install
> exit
> ```

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

error

**Comment by stfnhmplr** [comment]
There's another workaround in #85 that seems to work if git is not available.
