### ISSUE TITLE
Error Message "Device is not online"

### ISSUE THREAD

**Issue by marcel293** [stfnhmplr/homebridge-synology#66]
Hello,

thx for the plugin. Worked fine or the last months. I've changed to 2FA. Since that, I get the error message:

**_Device is not online; Polling disk temperature disabled.
Device is not online; Polling temperature disabled._**

            "name": "Diskstation",
            "host": "192.168.178.***",
            "mac": "00:00:00:00:00",
            "port": 5000,
            "username": "***",
            "password": "***",
            "protocol": "http",
            "version": "6.2.2",
            "startupTime": 60,
            "shutdownTime": 60,
            "otp": "16 character code",
            "accessory": "synology"

Does the plugin needs a special port or an extra release?
I checked the firewall - 5000 is open.

* **Plugin Version**: 0.5.0
* **Homebridge Version**: 1.3.8 
* **Node.js Version**: 16.13.0
* **NPM Version**: 6.14.11
* **Operating System**: Raspian Buster

**Comment by stfnhmplr** [comment]
> Does the plugin needs a special port or an extra release?
No, it should work out of the box. Which version did you use before? The messages you mentioned only occur when your diskstation is offline or cannot be pinged. They are not related to the 2FA, since they are created before a login attempt if the diskstation is not reachable via ping.
Can you manually check, if you can ping the diskstation from your Homebridge host? The entire log output would also be helpful.

**Comment by marcel293** [comment]
ICMP wasn't released in the firewall. I had to create a custom a firewall rule for ICMP. After this I could ping the DS again and the plugin works! It was not necessary in the past.
